docs/advanced/advanced.md, docs/architecture/architecture.md, docs/helm/helm.md, docs/quick-start/quick-start.md, docusaurus.config.js
=> Fix broken website link

docs/installation/network-options.md
Signed-off-by: Manuel Buil <mbuil@suse.com>
=> Update docs with dual-stack and ipv6 info

docs/installation/network-options.md
Updated network options with `wireguard-native` backend
=> Updated wireguard-native config

docusaurus.config.js
=> hotfix base url

docs/reference/server-config.md
Updated `--flannel-backend` deprecated values.
=> Updated flannel-backend deprecated values

docusaurus.config.js
=> Move to K3s Domain

CNAME, docusaurus.config.js
=> Add missing CNAME

.github/workflows/deploy.yml, CNAME, docusaurus.config.js
Fix based off https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-add-cname-file-cname
=> Move CNAME into GH Actions config

docs/security/hardening-guide.md
* Related to https://github.com/rancher/rke2/commit/bfcf7c7d30ad264b7940587ccb2a388a68d565c6 
* Will require a backport to 1.23/1.24 of https://github.com/k3s-io/k3s/pull/6253
=> Tidy up sample PSP/CR/CRB and add resources for ServiceLB dedicated SA

docs/reference/agent-config.md
=> Added tick to preserve formatting.

docs/installation/installation.md, docs/installation/network-options.md
Adds information about how to enable the revised VPN feature that we will support in the October release (and further)
Signed-off-by: Manuel Buil <mbuil@suse.com>
=> Add VPN info

docs/backup-restore/backup-restore.md, docs/installation/ha-embedded.md
- Remove experimental tags from 
- HA etcd clusters
- etcd backup and restore
=> Remove experimental tags from GA features

docusaurus.config.js, package.json, yarn.lock
- Adds local search: We will eventually get algolia search, but until that ticket gets resolved, having local search on the K3s docs is a huge improvement to no search.
- Bumps Docusaurus to v2.2.0
=> Add local search functionality 

docusaurus.config.js, src/css/custom.css, src/theme/Navbar/MobileSidebar/Header/index.js
**Old: Note that the search bar is stuck behind the GH link**
**New:**
=> Mobile navbar fix

docs/advanced/advanced.md, docs/installation/network-options.md, docs/networking/networking.md
Update rootless docs to cover https://github.com/k3s-io/k3s/pull/6498
=> Update rootless docs

i18n/zh/docusaurus-plugin-content-docs/current/reference/resource-profiling.md, i18n/zh/docusaurus-plugin-content-docs/current/upgrades/automated.md, i18n/zh/docusaurus-plugin-content-docs/current/upgrades/manual.md
Signed-off-by: vickyhella <vickyhella@hotmail.com>
=> Optimize Chinese translation

.github/workflows/test-deploy.yml, docs/advanced/advanced.md, docs/faq/faq.md, docs/installation/network-options.md, docs/reference/binary-tools.md, package.json, yarn.lock
- Sidesteps/fixes https://github.com/k3s-io/docs/issues/60. Its currently impossible to get a direct link the K3s channel due to admin settings on the Rancher Slack. So instead we give a link the to general Rancher Slack that actually works. 
- Adds an external link checker, which runs in CI and reports dead external links. See https://github.com/k3s-io/docs/actions/runs/3742731706/jobs/6354038001
=> Adjust FAQ Slack link + dead link checker

docs/advanced/advanced.md
Signed-off-by: Manuel Buil <mbuil@suse.com>
=> Add docs for network policy logging

.codespellignore, .github/workflows/codespell.yml, docs/advanced/advanced.md, docs/security/self-assessment.md, i18n/zh/docusaurus-plugin-content-docs/current/security/self-assessment.md
=> Add codespell

docs/advanced/advanced.md, docs/architecture/architecture.md, docs/installation/network-options.md, docs/quick-start/quick-start.md, docs/upgrades/manual.md
update rootless docs
be consistent about not calling things workers
add --disable-agent docs
add --egress-selector-mode docs
add nvidia runtime detection docs
=> Misc docs updates

docs/quick-start/quick-start.md
Noticed this while browsing the docs. Thought I'd just correct it.
=> Added missing space

docs/backup-restore/backup-restore.md
=> Update snapshot restore guide with HA steps

docs/reference/agent-config.md, docs/reference/server-config.md
Update help dump to v1.26.1
Addresses: https://github.com/k3s-io/docs/issues/76
=> Update agent and server reference

docs/backup-restore/backup-restore.md, i18n/zh/docusaurus-plugin-content-docs/current/advanced/advanced.md, i18n/zh/docusaurus-plugin-content-docs/current/backup-restore/backup-restore.md, i18n/zh/docusaurus-plugin-content-docs/current/reference/agent-config.md, i18n/zh/docusaurus-plugin-content-docs/current/reference/server-config.md, i18n/zh/docusaurus-plugin-content-docs/current/security/hardening-guide.md
This PR also changes some of the 2-space indents to 4-space indents just to facilitate my localization tool. The change doesn't affect the final effect. Sorry if it causes any confusion.
=> Update Chinese translation

docs/installation/airgap.md
This PR would fix the broken link with an extra dot.
Signed-off-by: imjoey <majunjie@apache.org>
=> Fix the broken link to get.k3s.io

docs/helm/helm.md, docs/installation/airgap.md, docs/upgrades/automated.md
Addresses https://github.com/k3s-io/docs/issues/80
Also reworded the automated upgrade page, using the new admonitions.
=> Updates to Helm and Automated Upgrade pages

docs/faq/faq.md
https://github.com/k3s-io/docs/pull/65 with DCO signed
=> Update slack link

docs/installation/network-options.md, docs/known-issues/known-issues.md
Closes: https://github.com/k3s-io/docs/issues/86
=> Add steps for upgrading hardened setups from v1.24 to v1.25

docs/networking/networking.md
Supersede https://github.com/k3s-io/docs/pull/75 with DCO signed (includes credit to original author)
=> ServiceLB Reword

docs/installation/requirements.md, yarn.lock
Addresses: https://github.com/k3s-io/k3s/issues/6708
Bump caniuse
=> Add section on Architectures

docs/installation/airgap.md
Related to https://github.com/k3s-io/k3s/issues/600
=> Mention the containerd assumption for air-gap deployments.

docusaurus.config.js
Changed according to the docs at https://docusaurus.io/docs/api/themes/configuration#respectPrefersColorScheme
=> Use system theme as default

docs/installation/server-roles.md, i18n/kr/docusaurus-plugin-content-docs/current/installation/server-roles.md
=> Fix etc(d) typo

i18n/zh/docusaurus-plugin-content-docs/current/reference/env-variables.md
change
`https://update.k3s.io/v1-release/channels。 => <https://update.k3s.io/v1-release/channels>。`
remove 。from url
=> Fix wrong url in ZH doc

docs/installation/configuration.md, docs/upgrades/manual.md
Based on feedback from https://github.com/k3s-io/k3s/issues/7593#issuecomment-1560518911
=> Make it more clear that the install script will clobber old config

docs/installation/network-options.md
Add important information about Cilium to avoid problems when nuking the k3s cluster
Fix canal link which was broken
=> Add cilium information and fix canal link

docs/reference/env-variables.md, i18n/zh/docusaurus-plugin-content-docs/current/architecture/architecture.md, i18n/zh/docusaurus-plugin-content-docs/current/datastore/ha-embedded.md, i18n/zh/docusaurus-plugin-content-docs/current/datastore/ha.md, i18n/zh/docusaurus-plugin-content-docs/current/installation/configuration.md, i18n/zh/docusaurus-plugin-content-docs/current/installation/network-options.md, i18n/zh/docusaurus-plugin-content-docs/current/installation/server-roles.md, i18n/zh/docusaurus-plugin-content-docs/current/upgrades/manual.md
Also fixed a URL in the EN doc according to #132
=> Update Chinese docs

docs/installation/airgap.md
Addresses https://github.com/k3s-io/k3s/issues/1144
=> Add example for dummy route in airgap

docs/datastore/ha-embedded.md, docs/datastore/ha.md, package.json, yarn.lock
- Attempt to address issues talked about offline that resulted from https://github.com/k3s-io/docs/pull/95
- Bump docusaurus dependencies
=> Rework section on Fixed Address Registration 

docs/installation/network-options.md
Adding tailscale docs. Tailscale integration will be out in the June releases
=> Add tailscale docs

docs/installation/network-options.md
=> Improve tailscale docs

docs/storage/storage.md, i18n/kr/docusaurus-plugin-content-docs/current/storage/storage.md, i18n/zh/docusaurus-plugin-content-docs/current/storage/storage.md
Replace the master version with a released version.
ref: https://github.com/longhorn/longhorn/issues/6428
=> Update Longhorn example installation link

.github/workflows/dependabot.yml, docs/backup-restore/backup-restore.md, docs/datastore/cluster-loadbalancer.md, docs/datastore/ha-embedded.md, docs/datastore/ha.md, docs/installation/datastore.md, docs/installation/disable-flags.md, docs/reference/agent-config.md, docs/reference/server-config.md, docusaurus.config.js, i18n/kr/docusaurus-plugin-content-docs/current/installation/datastore.md, i18n/kr/docusaurus-plugin-content-docs/current/installation/disable-flags.md, i18n/kr/docusaurus-plugin-content-docs/current/installation/ha-embedded.md, i18n/kr/docusaurus-plugin-content-docs/current/installation/ha.md, i18n/kr/docusaurus-plugin-content-docs/current/reference/agent-config.md, i18n/kr/docusaurus-plugin-content-docs/current/reference/server-config.md, sidebars.js
- Add dependabot to manage yarn dependecies 
- Remove all old pages, added automatic redirects
- Add guide on setting up an external loadbalancer with HAProxy or Nginx Community
Addresses: https://github.com/k3s-io/k3s/issues/5126
Currently hosted at: https://dereknola.github.io/docs-k3s/datastore/cluster-loadbalancer
=> Add guide on external load balancers

docusaurus.config.js, package.json, yarn.lock
Based of design discussion, we prefer to keep search local, and to utilize the highlight feature of local search.
Signed-off-by: Derek Nola [derek.nola@suse.com](mailto:derek.nola@suse.com)
=> Swap algolia for local search

docs/installation/network-options.md
Describe how to connect to headscale
=> Add description to connect to headscale

docs/helm/helm.md
Problem: given value example is wrong
Solution: give working example
=> improve helm timeout parameter description

docs/advanced/advanced.md, docs/architecture/architecture.md, docs/faq/faq.md, docs/installation/requirements.md
Addresses: https://github.com/k3s-io/docs/issues/165, https://github.com/k3s-io/docs/issues/119
=> Update faq with server/agent info

.github/workflows/release-notes.yml, docs/release-notes/v1.24.X.md, docs/release-notes/v1.25.X.md, docs/release-notes/v1.26.X.md, docs/release-notes/v1.27.X.md, docs/release-notes/v1.28.X.md, scripts/collect-all-release-notes.sh
=> New Release notes update

docs/helm.md
Addresses: https://github.com/k3s-io/docs/issues/218
=> Fix traefik example helm chart

.github/dependabot.yml, .github/workflows/dependabot.yml
Also removes incorrect dependabot config (wrong location)
=> [Dependabot] Configure group dependencies for docusaurous

docs/cli/agent.md, docs/cli/server.md, docs/installation/airgap.md, docs/installation/installation.md, docs/installation/network-options.md, docs/installation/private-registry.md, docs/installation/registry-mirror.md, docs/installation/requirements.md, docs/introduction.md, i18n/kr/docusaurus-plugin-content-docs/current/installation/airgap.md, i18n/kr/docusaurus-plugin-content-docs/current/installation/configuration.md, i18n/kr/docusaurus-plugin-content-docs/current/installation/installation.md, i18n/kr/docusaurus-plugin-content-docs/current/installation/network-options.md, i18n/kr/docusaurus-plugin-content-docs/current/installation/packaged-components.md, i18n/kr/docusaurus-plugin-content-docs/current/installation/private-registry.md, i18n/kr/docusaurus-plugin-content-docs/current/installation/registry-mirror.md, i18n/kr/docusaurus-plugin-content-docs/current/installation/requirements.md, i18n/zh/docusaurus-plugin-content-docs/current/installation/airgap.md, i18n/zh/docusaurus-plugin-content-docs/current/installation/configuration.md, i18n/zh/docusaurus-plugin-content-docs/current/installation/installation.md, i18n/zh/docusaurus-plugin-content-docs/current/installation/network-options.md, i18n/zh/docusaurus-plugin-content-docs/current/installation/packaged-components.md, i18n/zh/docusaurus-plugin-content-docs/current/installation/private-registry.md, i18n/zh/docusaurus-plugin-content-docs/current/installation/registry-mirror.md, i18n/zh/docusaurus-plugin-content-docs/current/installation/requirements.md, i18n/zh/docusaurus-plugin-content-docs/current/installation/server-roles.md, i18n/zh/docusaurus-plugin-content-docs/current/installation/uninstall.md, sidebars.js
Add docs for spegel embedded registry mirror, and tidy other docs sections that touch on registries or airgap.
=> Add docs for embedded registry mirror

docs/installation/registry-mirror.md
=> Fix ctr command examples

docs/installation/requirements.md
=> Add requirements section on suse linux distros

docs/storage.md
update doc longhorn version to latest 1.6.0
=> update doc longhorn version to 1.6.0

i18n/zh/docusaurus-plugin-content-docs/current/cli/server.md
For Istio doc PR ref need: https://github.com/istio/istio.io/pull/14827
=> Add cli help anchor for Istio ref need

docs/advanced.md
=> Fix typo rooless to rootless

docs/datastore/ha-embedded.md, docs/quick-start.md, docs/related-projects.md
- Add more related and use projects in the K3s community
- Replicate 'etcd odd number' dropdown from RKE2 docs
=> Rework related projects page

docs/advanced.md
[gpu-feature-discovery](https://github.com/NVIDIA/gpu-feature-discovery) is archived as it was integrated into the [k8s-device-plugin](https://github.com/NVIDIA/k8s-device-plugin).
=> Remove old dependency in advanced.md

docs/networking/networking-services.md
* Ref: https://github.com/k3s-io/docs/issues/292
Should hopefully help folks better understand how the traefik service and ingress status are related. I don't think we should list all the things you **can't** do with traefik, but I guess we could at least provide a more concrete example of what you **can** do.
=> Reference ServiceLB lbpool docs from Traefik section

docs/installation/airgap.md, i18n/zh/docusaurus-plugin-content-docs/current/installation/airgap.md
=> Fix typo in "Manually Deploy Images Method"

docs/networking/distributed-multicloud.md
I spent quite some time in figuring it out until I realized I need to set ACL rules in tailscale.
=> docs: added information to setup the tailscale VPN

docs/networking/networking-services.md
Explain a bit better the two uses cases that can happen and how the traffic flows for each of them
=> Update K3s Service Load Balancer docs

docs/cli/server.md
Ref:
* https://github.com/k3s-io/docs/issues/345
=> fix #345: add documentation for `--write-kubeconfig-group` option

docs/installation/airgap.md, docs/installation/registry-mirror.md
This PR:
* Fills the gaps with the RKE2 docs https://github.com/rancher/rke2-docs/pull/296
* Adds the GA information
=> Sync with the rke2 information about embedded registry

docs/related-projects.md
https://github.com/vitobotta/hetzner-k3s is a very popular tool (2K+ stars) that helps handle the nitty gritty of deploying to hetzner cloud
=> Add hetzner-k3s to related projects

.codespellrc, blog/2025-03-25-K3s-initialization.md, blog/authors.yml
=> Add blog post about K3s bootstrap

.github/workflows/codespell.yml, README.md, docs/advanced.md, docs/helm.md, docs/networking/networking-services.md, package.json
Update helm and containerd template docs to sync with recent changes to helm-controller and containerd 2.0. Also address some nits on token/proxy/ccm.
=> Update misc docs pages

docs/networking/basic-network-options.md
Included the agent specific flag for flannel on the Network options page.
=> Added Flannel Agent specific flag on network oprions

docs/datastore/datastore.md
https://github.com/k3s-io/docs/issues/409
=> Update list of datastores

docs/installation/airgap.md
Documenting the new feature to import airgap images conditionally
=> Add conditional importing airgap image feature

docs/advanced.md
The url is 404 since a few days
=> Fix non-existing url

docs/installation/configuration.md
Try to document the kubelet config feature: https://github.com/k3s-io/k3s/issues/2116
=> Describe the options to change kubelet configuration

docs/advanced.md, docs/installation/airgap.md
Expand a bit the SELinux documentation and use newer versions of the links
=> Improve selinux docs

docs/advanced.md, docs/cli/etcd-snapshot.md, docs/cluster-access.md, docs/installation/configuration.md, docs/known-issues.md, docs/networking/networking-services.md, docs/quick-start.md, docs/security/self-assessment-1.23.md, docs/security/self-assessment-1.24.md, docs/security/self-assessment-1.7.md, docs/security/self-assessment-1.8.md, docs/upgrades/automated.md, docusaurus.config.js, scripts/kubebench-to-markdown.sh
Misc fixes/improvements that I've had in my backlog
=> Misc fixes/updates

docs/advanced.md, docs/cli/certificate.md, docs/faq.md, docs/networking/networking-services.md, docs/release-notes-old/v1.24.X.md, docs/release-notes-old/v1.25.X.md, docs/release-notes-old/v1.26.X.md, docs/release-notes/v1.31.X.md, i18n/ja/docusaurus-plugin-content-docs/current/advanced.md, i18n/ja/docusaurus-plugin-content-docs/current/cli/certificate.md, i18n/ja/docusaurus-plugin-content-docs/current/faq.md, i18n/ja/docusaurus-plugin-content-docs/current/networking/networking-services.md, i18n/ja/docusaurus-plugin-content-docs/current/release-notes/v1.24.X.md, i18n/ja/docusaurus-plugin-content-docs/current/release-notes/v1.25.X.md, i18n/ja/docusaurus-plugin-content-docs/current/release-notes/v1.26.X.md, i18n/zh/docusaurus-plugin-content-docs/current/advanced.md, i18n/zh/docusaurus-plugin-content-docs/current/cli/certificate.md, i18n/zh/docusaurus-plugin-content-docs/current/faq.md, i18n/zh/docusaurus-plugin-content-docs/current/networking.md, i18n/zh/docusaurus-plugin-content-docs/current/networking/networking-services.md
k3s repo has migrated to `main`
=> Migrate from k3s-io master to main links

.github/workflows/browserlist.yml, .github/workflows/release-notes.yml, docs/release-notes-old/v1.24.X.md, docs/release-notes-old/v1.25.X.md, docs/release-notes-old/v1.26.X.md, docs/release-notes-old/v1.27.X.md, docs/release-notes-old/v1.28.X.md, docs/release-notes-old/v1.29.X.md, docs/release-notes/v1.30.X.md, docs/release-notes/v1.31.X.md, docs/release-notes/v1.32.X.md, docs/release-notes/v1.33.X.md, docs/release-notes/v1.34.X.md, scripts/collect-all-release-notes.sh
=> Add Release notes v1.34 page
