- docs/installation/ha-embedded.md
- docs/installation/ha.md
- docs/installation/installation.md
- docs/installation/kube-dashboard.md
- docs/networking/networking.md
During the conversion to the K3s docs website, several K3s Docs PRs merged into the old Rancher Docs page. This pulls in:
https://github.com/rancher/docs/pull/4175
https://github.com/rancher/docs/pull/4181
https://github.com/rancher/docs/pull/4186
> Pull in K3s PRs from rancher docs

- docs/installation/datastore.md
- docs/security/hardening-guide.md
Complete rancher docs issue: https://github.com/rancher/docs/issues/4204
Add newer versions of external DB validation: https://github.com/k3s-io/k3s/issues/5859
> Add new Database validations + Network harden

- docs/advanced/advanced.md
- docs/backup-restore/backup-restore.md
- docs/faq/faq.md
- docs/helm/helm.md
- docs/installation/airgap.md
- docs/installation/configuration.md
- docs/installation/ha.md
- docs/installation/installation.md
- docs/installation/network-options.md
- docs/installation/requirements.md
- docs/known-issues/known-issues.md
- docs/networking/networking.md
- docs/quick-start/quick-start.md
- docs/reference/binary-tools.md
- docs/reference/env-variables.md
- docs/security/hardening-guide.md
- docs/security/security.md
- docs/upgrades/automated.md
- docs/upgrades/manual.md
- docs/upgrades/upgrades.md
- docusaurus.config.js
This fixes the broken website at https://k3s-io.github.io/docs/ (the name of the repository) and now makes that the landing page (pending custom DNS configuration)
The actual docs will now sit at https://k3s-io.github.io/docs/docs.
This change broke all the internal links, because they were coded as absolute paths. 
Following [guidelines from Docusaurus](https://docusaurus.io/docs/markdown-features/links) these have been converted to "relative" links. This prevents having to fix the links in the future with any changes to the baseUrl
> Fix to website baseUrl + Relative Internal Links

- docs/security/secrets-encryption.md
Add a info section noting that if planning on using secrets-encryption, you need to enable it from the start.
Pulling in the "idea" of https://github.com/rancher/docs/pull/4202, not its exact change. 
> Add blurp about enabling secrets-encryption on install

- .gitignore
- README.md
- docs/installation/airgap.md
- docs/installation/disable-flags.md
- docs/installation/ha.md
- docs/installation/private-registry.md
- docs/networking/networking.md
- docs/reference/resource-profiling.md
- Convert any heading 1 (i.e. # HEADING) to heading 2 ( ## HEADING) to enable automatic sidebar generation. 
- Updated the README from the generic Rancher Docusaurus template.
> Fix Automatic Markdown Sidebar

- docs/reference/agent-config.md
- docs/reference/server-config.md
- docs/security/secrets-encryption.md
- The `--docker` flag has been changed, it was experimental -> deprecated -> experimental again (now with cri-dockerd).
- Clarification on how to kill and restart K3s in secrets encryption.
> Cleanup of Secrets Encryption Instructions, Docker Flag Fixes

- README.md
- docs/advanced/advanced.md
- docs/backup-restore/backup-restore.md
- docs/introduction.md
- Add more info in the README
- Cleanup docker section, we already bundle crictl in K3s, no need to install it. 
- Reword sections of the Introduction Page
- Add bullet pointed list instead of a long sentence
- Rework bullet points to be more descriptive about each component.
> Cleanup Introduction Page

- docs/advanced/advanced.md
- docs/helm/helm.md
Cleaned up the SELinux section, removing old instructions on pre-1.19 versions, using tabs to default to automatic installation (what most people will be using)
**OLD:**
**NEW:**
Cleanup the Helm page, removing reference to very old K3s versions and fixing spelling errors.
> Cleanup the SELinux and Helm sections

- docs/installation/configuration.md
There is a very hard to debug edge cases where if server flags don't match, the error message is highly misleading referencing Cluster CA certs.
Adding first draft of helpful notes for other users. I am open to all suggestions and edits from maintainers - thank you for a great project!
I burned about a day trying to debug TLS certs, rotate the CA and fight with the node installs. My k3s would fail to come up with errors:
```
Nov 01 23:09:14 elude2 systemd[1]: Starting Lightweight Kubernetes...
Nov 01 23:09:14 elude2 sh[371507]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
Nov 01 23:09:14 elude2 sh[371508]: Failed to get unit file state for nm-cloud-setup.service: No such file or directory
Nov 01 23:09:14 elude2 k3s[371511]: time="2022-11-01T23:09:14-06:00" level=info …
```
> Add details about flag mismatch

- docs/installation/network-options.md
Updated network options for dualstack removed `node-ip` as required option.
> update network options for dualstack

- docs/advanced/advanced.md
- docs/faq/faq.md
- docs/installation/network-options.md
- docs/installation/requirements.md
- docs/networking/networking.md
* Update flannel docs to cover recent backend changes/deprecations.
* Update servicelb docs to add long-overdue coverage for https://github.com/k3s-io/k3s/pull/5185.
Signed-off-by: Brad Davidson <brad.davidson@rancher.com>
> Update flannel/servicelb docs

- .github/workflows/test-deploy.yml
- docs/advanced/advanced.md
- docs/backup-restore/backup-restore.md
- docs/faq/faq.md
- docs/helm/helm.md
- docs/installation/airgap.md
- docs/installation/configuration.md
- docs/installation/ha.md
- docs/installation/network-options.md
- docs/installation/requirements.md
- docs/known-issues/known-issues.md
- docs/networking/networking.md
- docs/quick-start/quick-start.md
- docs/reference/binary-tools.md
- docs/reference/env-variables.md
- docs/security/secrets-encryption.md
- package.json
- yarn.lock
After some discussion on broken markdown links in https://github.com/k3s-io/docs/pull/56 I went looking for a solution. 
After finding https://github.com/facebook/docusaurus/issues/3321, `remark` has been added as an internal link checker.
See example failure: https://github.com/k3s-io/docs/actions/runs/3624584696/jobs/6111717898
All internal links are now fixed.
> Add internal link checker

- .github/workflows/deploy.yml
- .github/workflows/test-deploy.yml
- docs/security/hardening-guide.md
Addresses https://github.com/k3s-io/docs/issues/41
- Use tabs to rework hardening guide sections
- Section on K3s 1.25+ and the relevant PSA configuration
- Move the K3s "hardened flags" up on the guide, push reference details down. 
- Hardened flags are now provided as a `config.yaml`, the user is already doing prep work on the node, placing a premade config.yaml is inline with other prep work.
> Add section on CIS 1.23, PSA in K3s 1.25+ in hardening guide

- .github/workflows/deploy.yml
Since we use docusaraus for turning markdown to html, it is often difficult to review docs changes without the creator including screenshots, or the reviewer downloading the code change and building the website locally.... NO MORE!
Now developers can use the `workflow_dispatch` function to build specific branches and deploy them to personal github pages.
For example, my branch `can_test` is currently deployed to https://dereknola.github.io/docs-k3s/. Go check it out!
> Add Workflow dispatch with dev build options

- docs/security/hardening-guide.md
This has always been the default set, we just didn't explicitly pass it to the apiserver.
Ref: https://github.com/k3s-io/k3s/pull/6725
Signed-off-by: Brad Davidson <brad.davidson@rancher.com>
> Add default tls-cipher-suites values

- docs/advanced/advanced.md
Similar documentation already exists for RKE2: https://docs.rke2.io/advanced#configuring-an-http-proxy
> Document how to configure an HTTP proxy for K3s and Containerd

- docs/installation/network-options.md
The default `egress-selector-mode` used to be `pod`, but it was changed to `agent` a while back: https://github.com/k3s-io/k3s/commit/0581808f5c160b0c0cafec5b8f20430835f34f44 https://github.com/k3s-io/k3s/blob/master/pkg/cli/cmds/server.go#L229
This commit updates the docs to reflect the current default `egress-selector-mode`.
> Fix the default egress-selector-mode

- docs/architecture/architecture.md
- docs/faq/faq.md
- docs/installation/network-options.md
- docs/networking/networking.md
- docs/quick-start/quick-start.md
Addresses:
- https://github.com/k3s-io/k3s/issues/1049
- https://github.com/k3s-io/k3s/issues/1310
- https://github.com/k3s-io/k3s/issues/1308
- https://github.com/k3s-io/docs/issues/97
Other Changes:
- Clarifies which versions added dual-stack and ipv6 only support.
- Adds more information about how to get logs.
> Clarify Networking Documentation

- docs/faq/faq.md
- docs/installation/airgap.md
- docs/installation/private-registry.md
- docs/upgrades/automated.md
- docs/upgrades/manual.md
- https://github.com/k3s-io/k3s/issues/1802
- https://github.com/k3s-io/k3s/issues/1148
- https://github.com/k3s-io/k3s/issues/1103
- https://github.com/k3s-io/k3s/issues/3217
- Most of the questions around private registry use has already been resolved. I simply added additional clarification around public->private image redirection. 
- I cleaned up some bad wording around air-gap installs. Some steps were duplicated (such as install the k3s binary twice).
- Added note on K3s needing a default route, even in an air-gapped environment 
- Add FAQ about compatibility between different K3s versions.
> More docs backlog fixes

- docs/advanced/advanced.md
Didn't notice the double `.io` when tidying up this section.
> Fix kube-router annotation typo

- docs/installation/configuration.md
In the second line of  bash block  behind "When registering an agent, the following commands all result in the same behavior" was "K3s_TOKEN" instead of "K3S_TOKEN"
> Fixed Typo in Configuration.md

- docs/installation/network-options.md
A workaround to fix the issue is still being discussed. The new tentative release to fix it is 1.28, so we'd better remove the version in the docs to avoid confusion
> Remove version as issue still exists

- docs/installation/requirements.md
- docs/reference/resource-profiling.md
- Testing K3s resources requirements with update K3s version and new AWS instances (C6 is now cheaper/better than C5). Addresses https://github.com/k3s-io/k3s/issues/3976
- Updated ARM 4K page requirement to indicate new versions don't need it. Addresses: https://github.com/k3s-io/docs/issues/137
- Add note about SSDs on Raspberry PIs
> Update Resource Profiling to v1.26

- docs/networking/networking.md
Added a note on Network policy documentations related to the kube-router iptables rules that needs to be cleaned when K3s stopped.
issue: https://github.com/k3s-io/k3s/issues/7244
> Updated network policy documentation

- docs/datastore/datastore.md
- docs/installation/ha-embedded.md
- docs/installation/ha.md
- docs/installation/requirements.md
- docs/upgrades/manual.md
- docusaurus.config.js
- package.json
- yarn.lock
Addresses:
- https://github.com/k3s-io/k3s/issues/7808
- https://github.com/k3s-io/k3s/issues/7095
Adds client side redirect plugin (as server side redirection is not avaliable on GH pages), removing stub pages. Tested on all languages.  
Bumps dependencies
> Various fixes, page redirection, dependency bumps

- docs/installation/configuration.md
We mention using the `+` in a config but don't give a good example if it.
> Give example of append key to stringslice

- docs/helm/helm.md
Just a typo I stumbled upon while reading the docs.
> Fix typo in helm.md

- docs/cli/server.md
There is no `--disable-servicelb` flag. Instead, ServiceLB is disabled with the `--disable servicelb` flag and argument.
See [Using the `--disable` flag][1], **K3s Server CLI Help** at the bottom of the [`server` CLI page][2], and the [source code for the `server` flags][3].
[1]: https://docs.k3s.io/installation/packaged-components#using-the---disable-flag
[2]: https://docs.k3s.io/cli/server
[3]: https://github.com/k3s-io/k3s/blob/master/pkg/cli/cmds/server.go#L437
> Fix flag for disabling servicelb

- docs/networking/networking.md
Typo (ryn->run) I stumbled upon while reading the docs
> Fix typo in docs/networking.md

- docs/helm/helm.md
> Update helm fields

- docs/advanced/advanced.md
Adds a note for users who might be facing issues with admission webhooks when running servers with agent being disabled. 
Reference: https://github.com/k3s-io/k3s/discussions/8469
> Add an extra note for Agentless Mode

- docs/cli/server.md
Added IPv6 also on the `advertise-address` description because is a valid value in case IPv6 is the primary address for the service CIDR.
> Added IPv6 on the advertise-address description

- docs/cli/server.md
Previously, "K3s Server CLI Help" was not a hyperlink, and I think that's because it was prefixed with `#`, which is used for the title of the entire page.
I've changed it to `##` so that it will be header 2, and should show up as a clickable link and on the right hand side table of contents.
> Update server.md - make "K3s Server CLI Help" header a hyper link

- docs/installation/network-options.md
- docs/networking/networking.md
- docs/release-notes/v1.27.X.md
This PR does the following:
* Removes the option `--flannel-backend=wireguard` (deprecated since 1.24 and removed in 1.26)
* Hides the section "Migrating from `wireguard` or `ipsec` to `wireguard-native`" from the side summary
* Updates warning about dualStack node-ip
* Adds known issue when doing dualStack with IPv6 first
* Removes Multicluster CIDR
* Fixed this error thrown by CI:
```
./docs/release-notes/v1.27.X.md:134: porfile ==> profile
Error: Process completed with exit code 6[5](https://github.com/k3s-io/docs/actions/runs/6532077574/job/17734575997?pr=188#step:5:6).
```
> Networking content update

- i18n/zh/docusaurus-plugin-content-docs/current/architecture/architecture.md
The original version did not make sense in Chinese and was quite confusing. So I request to change it.
> Update Chinese architecture.md

- docs/advanced/advanced.md
- docs/installation/airgap.md
Addresses: https://github.com/k3s-io/docs/issues/190
> Add more information on Airgap + SELinux

- docs/installation/network-options.md
- i18n/kr/docusaurus-plugin-content-docs/current/installation/network-options.md
- i18n/zh/docusaurus-plugin-content-docs/current/installation/network-options.md
There is currently an overlap in the cluster-cidr and services-cidr: https://github.com/k3s-io/k3s/issues/8911
> Fix ipv6 notation and overlapping addresses

- docs/cli/secrets-encrypt.md
Add docs section for https://github.com/k3s-io/k3s/pull/8111
> Add section on secrets encryption v3

- docs/cli/token.md
> Add section on `k3s token rotate`

- docs/release-notes/v1.24.X.md
- scripts/collect-all-release-notes.sh
- Modify the release notes script to include a external link to the GH release page of each  patch release
- Update v1.24.X.md with new links above (all other release notes will be updated using the workflow bot)
> Embed GH release link in release notes

- docs/installation/network-options.md
A small fix that corrects the presentation of the Markdown table, as well as formatting the table.
> Fix installation network-options table

- docusaurus.config.js
- package.json
- yarn.lock
- Skip indexing of release notes pages, was filling up the search with unnecessary duplicate hits.
- Bump to Docusaurous 3.0.1
> Remove release notes from search, Docusaurous Bump

- docs/helm.md
The example for configuring the Traefik helm chart given here does not work, because the structure does not line up with the values file (the top-level `ports` node is missing). See here: https://github.com/traefik/traefik-helm-chart/blob/d9f4731fce7c8fdb134f417d977537e2ecad1a6e/traefik/values.yaml#L609
I am running `k3s version v1.28.5+k3s1 (5b2d1271)` which contains traefik-helm-chart `traefik-25.0.2+up25.0.0`.
For context:
The documentation here contains an example on how to configure the Helm charts that are shipped with K3s, that is through the `HelmChartConfig` CRD.
More specifically, it is an example that shows how to configure Traefik to trust, i.e. forward the `X-forwarded-*` headers if running behind another reverse proxy. It is exactly the use case I faced so I used it. My …
> Fix outdated/wrong HelmChartConfig example (regarding Traefik forwardedHeaders)

- .github/workflows/release-notes.yml
- docs/release-notes/v1.24.X.md
- docs/release-notes/v1.25.X.md
- docs/release-notes/v1.26.X.md
- docs/release-notes/v1.27.X.md
- docs/release-notes/v1.28.X.md
- docs/release-notes/v1.29.X.md
- scripts/collect-all-release-notes.sh
- Adds sidebar ordering to release notes script. Release are ordered in reverse numerical order, with the most recent Minor being at placed at the top.
- Update release notes automation with v1.26-v1.29
> Reverse order release notes in sidebar

- docs/installation/registry-mirror.md
`ctr image load` doesn't exist, not sure what I was thinking.
> Fix ctr commands again

- docs/installation/airgap.md
Fixes https://github.com/k3s-io/docs/issues/244
This fixes an invalid URL issue that `curl` throws. 
```console
$ sudo curl -L -O /var/lib/rancher/k3s/agent/images/k3s-airgap-images-amd64.tar.zst https://github.com/k3s-io/k3s/releases/download/v1.29.1-rc2%2Bk3s1/k3s-airgap-images-amd64.tar.zst
curl: (3) URL using bad/illegal format or missing URL
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
```
Since we are already passing the full path to the images.tar.zst, we can use `-o` instead of `-O`
> Fix the `curl` command for preparing k3s images for Airgap

- docs/installation/registry-mirror.md
We've intentionally disabled distributed mirroring of the latest tag, we should document that.
> Add note about latest tag

- docs/installation/private-registry.md
- docs/installation/registry-mirror.md
Technically this has been supported by containerd for a long time, but we never documented or tested it. Ref:
* https://github.com/containerd/containerd/blob/release/1.7/docs/hosts.md#setup-default-mirror-for-all-registries
> `Optionally the _default registry host namespace can be used as a fallback, if no other namespace matches.`
* https://github.com/containerd/containerd/blob/release/1.6/docs/cri/registry.md#configure-registry-endpoint
> `* is configured, and gcr.io is not: endpoints for * + default endpoint https://gcr.io/v2.`
Also adds a mention of the two unsupported K3S_PTP env vars.
> Add docs on wildcard registry

- .codespellrc
- docs/release-notes/v1.26.X.md
- docs/release-notes/v1.27.X.md
- docs/release-notes/v1.28.X.md
- docs/upgrades/killall.md
- docs/upgrades/manual.md
Addresses: https://github.com/k3s-io/docs/issues/178
~~Mentions that you have to stop the existing K3s service before running the installation script with a new version.~~
> Update manual upgrade page with better order of operations

- docs/datastore/cluster-loadbalancer.md
- docs/installation/installation.md
- docs/networking/basic-network-options.md
- docs/networking/distributed-multicloud.md
- docs/networking/multus-ipams.md
- docs/networking/networking-services.md
- docs/networking/networking.md
- docusaurus.config.js
- i18n/kr/docusaurus-plugin-content-docs/current/datastore/cluster-loadbalancer.md
- i18n/kr/docusaurus-plugin-content-docs/current/installation/installation.md
- i18n/kr/docusaurus-plugin-content-docs/current/networking.md
- i18n/kr/docusaurus-plugin-content-docs/current/networking/basic-network-options.md
- i18n/kr/docusaurus-plugin-content-docs/current/networking/distributed-multicloud.md
- i18n/kr/docusaurus-plugin-content-docs/current/networking/multus-ipams.md
- i18n/kr/docusaurus-plugin-content-docs/current/networking/networking-services.md
- i18n/kr/docusaurus-plugin-content-docs/current/networking/networking.md
- i18n/zh/docusaurus-plugin-content-docs/current/datastore/cluster-loadbalancer.md
- i18n/zh/docusaurus-plugin-content-docs/current/installation/installation.md
- i18n/zh/docusaurus-plugin-content-docs/current/networking.md
- i18n/zh/docusaurus-plugin-content-docs/current/networking/basic-network-options.md
- i18n/zh/docusaurus-plugin-content-docs/current/networking/distributed-multicloud.md
- i18n/zh/docusaurus-plugin-content-docs/current/networking/multus-ipams.md
- i18n/zh/docusaurus-plugin-content-docs/current/networking/networking-services.md
- i18n/zh/docusaurus-plugin-content-docs/current/networking/networking.md
- package.json
- sidebars.js
- yarn.lock
This PR adds information about how to use Multus with additional IPAMs (e.g. whereabouts).
Moreover, it consolidates all networking information in the Networking tab, which has three different sections:
* Basic Network Options
* Distributed hybrid or multicloud cluster
* Multus and IPAM plugins
* Networking Services
The networking information under installation gets removed
Having all together felt too much for just one document
> Organize network docs differently and add Multus

- docs/upgrades/automated.md
> Add instruction to deploy system-upgrade-controller CRD

- docs/security/hardening-guide.md
- docs/upgrades/manual.md
- i18n/zh/docusaurus-plugin-content-docs/current/known-issues.md
Correct the typos in the documentation: change `verision` to `version` and `PodSecurityPoliciy` to `PodSecurityPolicy`.
> Fix typo in documentation

- docs/datastore/cluster-loadbalancer.md
Since we are installing the Nginx loadbalancer on lb-1 with the IP 10.10.10.98, we need to use this IP as the server registration IP for our agent nodes, not the IP of lb-2.
> Fix IP of Nginx loadbalancer for server registration

- .github/workflows/release-notes.yml
- docs/release-notes/v1.27.X.md
- docs/release-notes/v1.28.X.md
- docs/release-notes/v1.29.X.md
- docs/release-notes/v1.30.X.md
- Since we can't trigger CI when we automatically open a PR for release-notes (recursion prevention), we need to check spellcheck first before allowing the PR to be opened. 
- Spelling fixes in Releases
> Run spellcheck before attempting to open a PR on release notes

- docs/cli/etcd-snapshot.md
This change replaces the `etcd-snapshot` subcommand with `etcd-snapshot save` in the example, to conform with what the note indicates:
https://github.com/k3s-io/docs/blob/492ecff6ee19f00a84c7e306d5c0c71cd8edaab4/docs/cli/etcd-snapshot.md?plain=1#L144
> Replace `etcd-snapshot` with `etcd-snapshot save`

- docs/datastore/ha.md
The original document can mislead the user and lead to some errors
> docs: Optimize and fix HA External DB document

- docs/known-issues.md
- docs/security/hardening-guide.md
- i18n/kr/docusaurus-plugin-content-docs/current/known-issues.md
- i18n/kr/docusaurus-plugin-content-docs/current/security/hardening-guide.md
- i18n/zh/docusaurus-plugin-content-docs/current/known-issues.md
- i18n/zh/docusaurus-plugin-content-docs/current/security/hardening-guide.md
CIS [recommends](https://github.com/k3s-io/docs/blob/main/docs/security/self-assessment.md#1224-ensure-that-the---service-account-lookup-argument-is-set-to-true-automated) to set the --service-account-lookup parameter to true or *remove it from the config file so that the default applies*. 
This parameter is enabled by default already since [kubernetes #44071](https://github.com/kubernetes/kubernetes/pull/44071). Therefore I propose to remove this parameter from the example configuration in the hardening guide.
> Remove unnecessary 'service-account-lookup=true' from hardening guide

- docs/known-issues.md
- docs/security/hardening-guide.md
- i18n/kr/docusaurus-plugin-content-docs/current/known-issues.md
- i18n/kr/docusaurus-plugin-content-docs/current/security/hardening-guide.md
- i18n/kr/docusaurus-plugin-content-docs/current/security/self-assessment-1.23.md
- i18n/zh/docusaurus-plugin-content-docs/current/known-issues.md
- i18n/zh/docusaurus-plugin-content-docs/current/security/hardening-guide.md
CIS [recommends](https://github.com/k3s-io/docs/blob/main/docs/security/hardening-guide.md#control-1226) to set the `--request-timeout` parameter *only when necessary*. The default already limits requests to 60 seconds and increasing this would not improve the security. Hence, the suggestion to increase this parameter to 300 seconds should be removed from the hardening guide.
> Remove unnecessary 'request-timeout=300s' parameter from CIS hardening guide

- docs/cli/etcd-snapshot.md
- docs/cli/secrets-encrypt.md
- docs/datastore/cluster-loadbalancer.md
- docs/datastore/datastore.md
- docs/installation/airgap.md
- docs/installation/requirements.md
- docs/networking/basic-network-options.md
- i18n/kr/docusaurus-plugin-content-docs/current/advanced.md
- i18n/kr/docusaurus-plugin-content-docs/current/architecture.md
- i18n/kr/docusaurus-plugin-content-docs/current/cli/server.md
- i18n/kr/docusaurus-plugin-content-docs/current/faq.md
- i18n/kr/docusaurus-plugin-content-docs/current/known-issues.md
- i18n/kr/docusaurus-plugin-content-docs/current/networking/basic-network-options.md
- i18n/zh/docusaurus-plugin-content-docs/current/installation/network-options.md
- i18n/zh/docusaurus-plugin-content-docs/current/networking/basic-network-options.md
- Ubuntu 24.04 no longer requires the extra modules for vxlan on Raspberry Pi
- Added more queryString support to make linking to specific tabs easier
> Add notice for Ubuntu 24.04 on Raspberry Pi

- docs/security/hardening-guide.md
- docs/security/security.md
- docs/security/self-assessment-1.24.md
- docs/security/self-assessment-1.7.md
- docs/security/self-assessment-1.8.md
- scripts/kubebench-to-markdown.sh
This is  the result of an effort to overhaul RKE2 and K3s CIS scans in [rancher/security-scan](https://github.com/rancher/security-scan)
The changes here are a direct result of PRs implemented in the above repo. 
Its easiest to see the changes by looking at a live version of the site hosted at https://dereknola.github.io/docs-k3s/security
Addresses: https://github.com/k3s-io/docs/issues/306
> Overhaul of CIS Pages

- .github/workflows/deploy.yml
- .github/workflows/release-notes.yml
- the new cron job was opening PRs on dev forks.
> Only run release-notes PR automatically on k3s-io

- docs/datastore/cluster-loadbalancer.md
Add script security option for the keepalived (required in current version of the daemon)
When not configured, keepalived emits a security violation error at start:
```
Aug 12 11:24:26 k3s-lb-test-1 Keepalived_vrrp[11314]: WARNING - default user 'keepalived_script' for script execution does not exist - please create.
Aug 12 11:24:26 k3s-lb-test-1 Keepalived_vrrp[11314]: SECURITY VIOLATION - scripts are being executed but script_security not enabled.
Aug 12 11:24:26 k3s-lb-test-1 Keepalived_vrrp[11314]: VRRP_Script(chk_haproxy) succeeded
Aug 12 11:24:26 k3s-lb-test-1 Keepalived_vrrp[11314]: (haproxy-vip) Entering BACKUP STATE
```
> update keepalived config example

- .github/workflows/release-notes.yml
- docs/release-notes/v1.24.X.md
- docs/release-notes/v1.25.X.md
- docs/release-notes/v1.26.X.md
- docs/release-notes/v1.27.X.md
- docs/release-notes/v1.28.X.md
- docs/release-notes/v1.29.X.md
- docs/release-notes/v1.30.X.md
- docs/release-notes/v1.31.X.md
- package.json
- scripts/collect-all-release-notes.sh
- yarn.lock
- Bump docusaurus/theme-common, dependabot seems to skip this for some reason
> Add v1.31 release notes page

- docs/storage.md
Relevant docs page: https://docs.k3s.io/storage
if you read the previous section (Local Storage Provider) the order is:
1. create yaml files
2. apply yaml
3. confirm changes
But the longhorn section has the ordering:
1. install Longhorn
2. apply yaml files
3. define yaml files
4. confirm changes
I believe steps 2 and 3 are erroneously in the wrong order.
> reorder documentation steps

- docs/known-issues.md
With the releases of [security-scan v0.2.17](https://github.com/rancher/security-scan/releases/tag/v0.2.17), the checks no longer look for `make-iptables-util-chains` explicitly (as its nonexistence is also allowed).
> Remove lingering make-iptables-util-chains reference

- docs/networking/basic-network-options.md
I run a cluster in dual stack mode using a cidr from the ULA range following the dual stack docs. Using [these](https://docs.k3s.io/networking/basic-network-options#dual-stack-ipv4--ipv6-networking) instructions, I noticed that pods use their pod IP for (cluster-external) outgoing connections, in this case meaning a ULA address, which obviously does not work. What I intended is that they use the host's address. After some googling, I found the `--flannel-ipv6-masq` option that does what I want. It is documented in the flannel section: https://docs.k3s.io/networking/basic-network-options#flannel-options. However, I think this should also be mentioned in the dual stack and single stack sections, as it is not given that people also read the flannel section.
This PR adds a mention of the need …
> IPv6 networking: mention --flannel-ipv6-masq in dual stack and single stack ipv6 section

- docs/cli/token.md
Token regex was rendered as `"[a-z0-9]6.[a-z0-9]16"` instead of `[a-z0-9]{6}.[a-z0-9]{16}`
> docs: Fix rendering for token regex

- .github/workflows/test-deploy.yml
- package.json
- yarn.lock
remarks-lint-no-dead-urls has been updated to handle "stable" site redirects. We can once again catch errors and fail test deployments. There is still a weird issue around some anchors and certain sites like mysql, so those have been added to an exception list.
> Bump remark-lint-no-dead-urls, readd error on failure

- README.md
- docs/advanced.md
- docs/cli/token.md
- docs/installation/uninstall.md
- docs/networking/multus-ipams.md
- docs/networking/networking-services.md
* Use HelmChart for deployment
* Include improvements from https://github.com/k3s-io/k3s/pull/10868
* Add uninstall caution
* Fix typos and outdated commands
Issues:
* https://github.com/k3s-io/docs/issues/341
* https://github.com/k3s-io/docs/issues/343
* https://github.com/k3s-io/docs/issues/304
> Update Multus docs

- docs/reference/env-variables.md
- This PR will add more info about the runtimes search in the new release that is coming from October
- I will wait for the releases and then merge the PR when got the approves
@dereknola do you think it is better to add a new place for the runtimes or we can add in the reference part? 
btw I feel like that `After October release` is not a very good thing to be wrote, should I add the versions?
> Add runtimes in reference

- docs/advanced.md
- docs/installation/private-registry.md
Ref for the rewrite stuff: 
* https://github.com/rancher/wharfie/issues/25
I will be PRing similar changes into the RKE2 docs since it keeps coming up.
> Update docs for custom runtimes and registry rewrites

- docs/security/hardening-guide.md
Corrected namespaceSelector for intra-namespace network policy example. The label "name" does not exist on the namespace resource kube-system, but the label "kubernetes.io/metadata.name" is present.
> Corrected namespaceSelector for network policy

- docs/cli/etcd-snapshot.md
Rework docs, and add documentation for ETCDSnapshotFiles and S3 config secret
* https://github.com/k3s-io/docs/issues/347
* https://github.com/k3s-io/k3s/pull/10340
* https://github.com/k3s-io/k3s/pull/8064
Page now has proper section layout to support autogenerated TOC:
> Rework snapshot docs

- docs/installation/requirements.md
It's not `VCPUS`, it should be: `vCPUs`
> It's called vCPUs

- docs/networking/networking-services.md
Describe how we could preserve the client source IP
> Add the warning for externalTrafficPolicy=Local

- docs/cli/token.md
Added some extra information which could be useful for other users
> Add useful information for tokens

- docs/cli/token.md
Related to https://github.com/k3s-io/k3s/issues/11674, this PR specifies that the `k3s token` CLI tool is for bootstrap tokens and to rotate the server token. With the current description, users can easily think that it is only used for bootstrap tokens or that the `token rotate` replaces the server token with a bootstrap token
> Clarify the usage of the k3s token CLI tool

- docs/security/hardening-guide.md
- sidebars.js
This PR hides the old cis1-24 and removes information related to traefikv1 and kubernetes 1.20 and older
> Hide old cis and remove 1.20 information

- .github/workflows/browserlist.yml
- .github/workflows/release-notes.yml
It's confusing when its run inside the Release Notes automated CI. Instead run it as a monthly cron job.
> Seperate Browserslist DB update into monthly CI

- docs/installation/configuration.md
The existing text stating that configuration files "will be used on install" apparently suggested to some users that config files *will not* be used *after* installation.
Address that, and tweak the language on drop-in config files a bit.
> Clarify config file loading

- docs/advanced.md
Added warning about current issue to network policy logging. If the network policy uses a wildcard for all pods `podSelector: {}`, logging does not work correctly.
[Referencing #8008](https://github.com/k3s-io/k3s/issues/8008)
> Added warning about issue to netpol logging

- docs/cli/certificate.md
Add missing information about the "k3s certificate expiration" command in the docs. Based on a user confusion
> Add information about the expiration data of certificates

- docs/storage.md
Kubernetes is not maintaining in-tree volume plugins anymore, we should remove that information from the docs
> Remove outdated storage information

- docs/installation/airgap.md
- docs/installation/registry-mirror.md
- package.json
- yarn.lock
- Use tabs to better organize airgap page
- Embrace the guided format of the page and use numbers for major steps.
> Use tabs and guide structure for airgap install page

- docs/networking/basic-network-options.md
2001:db8::/32 is the reserved documentation range, which should be used instead of a range that might be assigned to someone. See https://en.wikipedia.org/wiki/Reserved_IP_addresses#IPv6 for details.
We can't fix the v4 addresses since there are only some documentation /24s and nothing larger.
> basic-network-options: use v6 example ranges

- docs/cli/etcd-snapshot.md
- OBS: it will be merged only after the august release, so it will sit here in the mean time.
Decided to create a new sub part in s3 docs, since it have a version gate and for easy access.
> Add s3 retention flag to the docs

- blog/2025-08-30-K3s-1.34-release.md
Prepare a blog with our release
> Add blogpost in sync with the v1.34 Kubernetes release

- docs/upgrades/manual.md
Continues https://github.com/k3s-io/docs/pull/381
> Update notes on pod cordon and drain
